#!/usr/bin/env bash
# End-to-end: wait for funds, deploy all 7 contracts to Monad testnet, then
# wire the addresses into the gateway and mock frontend. Idempotent — running
# twice after a successful deploy writes the already-deployed addresses again
# (a no-op unless you've since re-run `forge script` manually).
#
# Usage:
#   ./contracts/script/deploy-and-wire.sh
#
# Prereqs:
#   contracts/.env with DEPLOYER_ADDRESS, PRIVATE_KEY, MEDICAL_BOARD,
#   HOSPITAL_ADMIN, MONAD_TESTNET_RPC.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT/contracts"

# Load env
set -a; source .env; set +a

# ── 1. wait for funds (up to 30 min) ──────────────────────────────────────
echo "── checking deployer balance on Monad testnet …"
for i in $(seq 1 180); do
    bal=$(cast balance "$DEPLOYER_ADDRESS" --rpc-url "$MONAD_TESTNET_RPC" 2>/dev/null || echo "0")
    if [ "$bal" != "0" ] && [ -n "$bal" ]; then
        echo "  funded: $(cast from-wei "$bal") MON"
        break
    fi
    if [ $i -eq 180 ]; then
        echo "  timeout — fund $DEPLOYER_ADDRESS at https://faucet.monad.xyz and re-run"
        exit 1
    fi
    [ $((i % 6)) -eq 0 ] && echo "  still 0 MON after $((i * 10))s — waiting … (faucet: https://faucet.monad.xyz, addr: $DEPLOYER_ADDRESS)"
    sleep 10
done

# ── 2. deploy the suite ───────────────────────────────────────────────────
echo
echo "── deploying Polyglot-Attest suite on Monad testnet …"
mkdir -p deployments
DEPLOY_OUT="deployments/testnet-$(date +%Y%m%d-%H%M%S).log"
forge script script/Deploy.s.sol \
    --rpc-url "$MONAD_TESTNET_RPC" \
    --private-key "$PRIVATE_KEY" \
    --broadcast 2>&1 | tee "$DEPLOY_OUT"

# ── 3. parse addresses ────────────────────────────────────────────────────
parse() {
    grep -oE "$1\s+0x[a-fA-F0-9]{40}" "$DEPLOY_OUT" | awk '{print $NF}' | head -1
}

SBT_ADDR=$(parse "CredentialSBT")
CONSENT_ADDR=$(parse "ConsentRegistry")
MODELS_ADDR=$(parse "ModelRegistry")
ATTEST_ADDR=$(parse "InferenceAttestation")
DRIFT_ADDR=$(parse "DriftMonitor")
VAULT_ADDR=$(parse "ConsensusVault")
CDA_ADDR=$(parse "ClinicalDecisionAttest")

echo
echo "── parsed addresses ─────────────────────────────────────────────────"
echo "  CredentialSBT              $SBT_ADDR"
echo "  ConsentRegistry            $CONSENT_ADDR"
echo "  ModelRegistry              $MODELS_ADDR"
echo "  InferenceAttestation       $ATTEST_ADDR"
echo "  DriftMonitor               $DRIFT_ADDR"
echo "  ConsensusVault             $VAULT_ADDR"
echo "  ClinicalDecisionAttest.    $CDA_ADDR"

# ── 4. snapshot JSON (gitignored — sensitive addresses go in deployments/) ─
cat > "deployments/testnet-latest.json" <<EOF
{
  "network": "monad-testnet",
  "chainId": 20143,
  "rpc": "$MONAD_TESTNET_RPC",
  "explorer": "https://testnet.monadexplorer.com",
  "deployedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "deployer": "$DEPLOYER_ADDRESS",
  "contracts": {
    "CredentialSBT":              "$SBT_ADDR",
    "ConsentRegistry":            "$CONSENT_ADDR",
    "ModelRegistry":              "$MODELS_ADDR",
    "InferenceAttestation":       "$ATTEST_ADDR",
    "DriftMonitor":               "$DRIFT_ADDR",
    "ConsensusVault":             "$VAULT_ADDR",
    "ClinicalDecisionAttestation":"$CDA_ADDR"
  }
}
EOF
echo
echo "  → contracts/deployments/testnet-latest.json written"

# ── 5. wire gateway/.env ──────────────────────────────────────────────────
GATEWAY_ENV="$ROOT/gateway/.env"
[ -f "$GATEWAY_ENV" ] || cp "$ROOT/gateway/.env.example" "$GATEWAY_ENV"

update_env_var() {
    local key="$1"; local value="$2"; local file="$3"
    if grep -q "^${key}=" "$file"; then
        # macOS sed requires '' after -i
        sed -i '' "s|^${key}=.*|${key}=${value}|" "$file" 2>/dev/null \
            || sed -i "s|^${key}=.*|${key}=${value}|" "$file"
    else
        echo "${key}=${value}" >> "$file"
    fi
}

update_env_var "INFERENCE_ATTESTATION_ADDRESS" "$ATTEST_ADDR"      "$GATEWAY_ENV"
update_env_var "CONSENT_REGISTRY_ADDRESS"      "$CONSENT_ADDR"     "$GATEWAY_ENV"
update_env_var "MODEL_REGISTRY_ADDRESS"        "$MODELS_ADDR"      "$GATEWAY_ENV"
update_env_var "CREDENTIAL_SBT_ADDRESS"        "$SBT_ADDR"         "$GATEWAY_ENV"
update_env_var "CLINICAL_DECISION_ADDRESS"     "$CDA_ADDR"         "$GATEWAY_ENV"
update_env_var "MONAD_RPC_URL"                 "$MONAD_TESTNET_RPC" "$GATEWAY_ENV"
update_env_var "MONAD_CHAIN_ID"                "20143"             "$GATEWAY_ENV"
update_env_var "HOSPITAL_PRIVATE_KEY"          "$PRIVATE_KEY"      "$GATEWAY_ENV"

echo "  → gateway/.env updated with deployed addresses"

# ── 6. drop a frontend-consumable address manifest ───────────────────────
FRONT_MANIFEST="$ROOT/hospital-mockup/src/lib/chain.ts"
cat > "$FRONT_MANIFEST" <<EOF
// Auto-generated by contracts/script/deploy-and-wire.sh.
// Do not edit by hand; re-run the deploy to refresh.

export const CHAIN = {
  id: 20143,
  name: "Monad Testnet",
  rpc: "$MONAD_TESTNET_RPC",
  explorer: "https://testnet.monadexplorer.com",
} as const;

export const CONTRACTS = {
  CredentialSBT:                "$SBT_ADDR",
  ConsentRegistry:              "$CONSENT_ADDR",
  ModelRegistry:                "$MODELS_ADDR",
  InferenceAttestation:         "$ATTEST_ADDR",
  DriftMonitor:                 "$DRIFT_ADDR",
  ConsensusVault:               "$VAULT_ADDR",
  ClinicalDecisionAttestation:  "$CDA_ADDR",
} as const;

export function txUrl(hash: string): string {
  return \`\${CHAIN.explorer}/tx/\${hash}\`;
}

export function addressUrl(addr: string): string {
  return \`\${CHAIN.explorer}/address/\${addr}\`;
}
EOF
echo "  → hospital-mockup/src/lib/chain.ts written"

# ── 7. demo bootstrap: issue SBT + consent + register ensemble ────────────
echo
echo "── running post-deploy bootstrap (SBT + consent + 11 models) …"
export SBT_ADDRESS="$SBT_ADDR"
export CONSENT_ADDRESS="$CONSENT_ADDR"
export MODELS_ADDRESS="$MODELS_ADDR"
forge script script/BootstrapDemo.s.sol \
    --rpc-url "$MONAD_TESTNET_RPC" \
    --private-key "$PRIVATE_KEY" \
    --broadcast 2>&1 | tail -20

echo
echo "── done. Addresses live on Monad testnet."
echo "   Explorer: https://testnet.monadexplorer.com/address/$ATTEST_ADDR"
